// Generated by gencpp from file test/AddInts.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ADDINTS_H
#define TEST_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <test/AddIntsRequest.h>
#include <test/AddIntsResponse.h>


namespace test
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::test::AddInts&) { return value(); }
};

template<>
struct DataType< ::test::AddInts > {
  static const char* value()
  {
    return "test/AddInts";
  }

  static const char* value(const ::test::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::test::AddIntsRequest> should match
// service_traits::MD5Sum< ::test::AddInts >
template<>
struct MD5Sum< ::test::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::AddInts >::value();
  }
  static const char* value(const ::test::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::AddIntsRequest> should match
// service_traits::DataType< ::test::AddInts >
template<>
struct DataType< ::test::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::test::AddInts >::value();
  }
  static const char* value(const ::test::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::AddIntsResponse> should match
// service_traits::MD5Sum< ::test::AddInts >
template<>
struct MD5Sum< ::test::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::AddInts >::value();
  }
  static const char* value(const ::test::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::AddIntsResponse> should match
// service_traits::DataType< ::test::AddInts >
template<>
struct DataType< ::test::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::test::AddInts >::value();
  }
  static const char* value(const ::test::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_ADDINTS_H
